server:
  port: 8081
  servlet:
    context-path: /demo

spring:
  application:
    name: spring-boot-demo

info:
  hello: world
  name: ${spring.application.name}
  version: @version@

demo-properties:
  hello-msg: "Hello world!"
  helloMsgSv: "Hej världen!"
  json-placeholder-base-url: "https://jsonplaceholder.typicode.com"

---
spring:
  profiles: dev

demo-properties:
  hello-msg: "Different Hello world!"
